name: Build and Upload Java Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Replace with your required Java version
          distribution: 'temurin'

      # Step 3: Build JAR/WAR file
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Upload the artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-artifact
          path: target/*.jar # Replace with target/*.war if building a WAR file
